import {AudienceZoneTemplateModel} from './AudienceZoneTemplate.model';

/**
 * Represents a physical area or zone within a structure.
 * These are permanent spaces like stages, halls, rooms, etc.,
 * distinct from EventAudienceZones which are event-specific configurations.
 */
export interface StructureAreaModel {
  /**
   * The unique identifier for the area.
   * Generated by the backend.
   */
  id: number;

  /**
   * The name of the area.
   * @example "Main Stage", "Exhibition Hall A", "Room 101"
   */
  name: string;

  /**
   * Optional description of the area.
   */
  description?: string;

  /**
   * The maximum capacity of this area.
   */
  maxCapacity: number;

  /**
   * Indicates if the area is currently active and available for use.
   */
  active: boolean;

  /**
   * The identifier of the structure this area belongs to.
   */
  structureId: number;

  /**
   * Optional list of audience zone templates defined for this area.
   */
  audienceZoneTemplates?: AudienceZoneTemplateModel[];
}

/**
 * Data Transfer Object for creating a new Area.
 * 'id' is omitted as it will be generated by the backend.
 * 'structureId' will be provided contextually (e.g., from the URL parameter).
 */
export type AreaCreationDto = {
  name: string;
  description?: string;
  maxCapacity: number;
  isActive: boolean;
};

/**
 * Data Transfer Object for updating an existing Area.
 * All properties are optional for partial updates.
 * 'id' and 'structureId' are typically not updatable or provided via URL.
 */
export type AreaUpdateDto = Partial<AreaCreationDto>;
