name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Application
        run: |
          npm install
          # npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Static Server image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: novaenebulae/tickly-frontend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/tickly-deployment
            docker-compose pull static-server
            docker-compose up -d --no-deps static-server
            docker image prune -f
